/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppViewRouteImport } from './routes/_app.$view'
import { Route as AppViewIndexRouteImport } from './routes/_app.$view.index'
import { Route as AppViewMailboxIdThreadIdRouteImport } from './routes/_app.$view.$mailboxId.$threadId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppViewRoute = AppViewRouteImport.update({
  id: '/$view',
  path: '/$view',
  getParentRoute: () => AppRoute,
} as any)
const AppViewIndexRoute = AppViewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppViewRoute,
} as any)
const AppViewMailboxIdThreadIdRoute =
  AppViewMailboxIdThreadIdRouteImport.update({
    id: '/$mailboxId/$threadId',
    path: '/$mailboxId/$threadId',
    getParentRoute: () => AppViewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$view': typeof AppViewRouteWithChildren
  '/$view/': typeof AppViewIndexRoute
  '/$view/$mailboxId/$threadId': typeof AppViewMailboxIdThreadIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/$view': typeof AppViewIndexRoute
  '/$view/$mailboxId/$threadId': typeof AppViewMailboxIdThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$view': typeof AppViewRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/$view/': typeof AppViewIndexRoute
  '/_app/$view/$mailboxId/$threadId': typeof AppViewMailboxIdThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/$view' | '/$view/' | '/$view/$mailboxId/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/$view' | '/$view/$mailboxId/$threadId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$view'
    | '/_app/'
    | '/_app/$view/'
    | '/_app/$view/$mailboxId/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$view': {
      id: '/_app/$view'
      path: '/$view'
      fullPath: '/$view'
      preLoaderRoute: typeof AppViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$view/': {
      id: '/_app/$view/'
      path: '/'
      fullPath: '/$view/'
      preLoaderRoute: typeof AppViewIndexRouteImport
      parentRoute: typeof AppViewRoute
    }
    '/_app/$view/$mailboxId/$threadId': {
      id: '/_app/$view/$mailboxId/$threadId'
      path: '/$mailboxId/$threadId'
      fullPath: '/$view/$mailboxId/$threadId'
      preLoaderRoute: typeof AppViewMailboxIdThreadIdRouteImport
      parentRoute: typeof AppViewRoute
    }
  }
}

interface AppViewRouteChildren {
  AppViewIndexRoute: typeof AppViewIndexRoute
  AppViewMailboxIdThreadIdRoute: typeof AppViewMailboxIdThreadIdRoute
}

const AppViewRouteChildren: AppViewRouteChildren = {
  AppViewIndexRoute: AppViewIndexRoute,
  AppViewMailboxIdThreadIdRoute: AppViewMailboxIdThreadIdRoute,
}

const AppViewRouteWithChildren =
  AppViewRoute._addFileChildren(AppViewRouteChildren)

interface AppRouteChildren {
  AppViewRoute: typeof AppViewRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppViewRoute: AppViewRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
