/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppMailRouteImport } from './routes/_app._mail'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppMailIndexRouteImport } from './routes/_app._mail.index'
import { Route as AppMailViewRouteImport } from './routes/_app._mail.$view'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminAddressesRouteImport } from './routes/_app.admin.addresses'
import { Route as AppAdminDomainsRouteImport } from './routes/_app.admin.domains'
import { Route as AppAdminPeopleRouteImport } from './routes/_app.admin.people'
import { Route as AppMailViewIndexRouteImport } from './routes/_app._mail.$view.index'
import { Route as AppMailViewMailboxIdThreadIdRouteImport } from './routes/_app._mail.$view.$mailboxId.$threadId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMailRoute = AppMailRouteImport.update({
  id: '/_mail',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppMailIndexRoute = AppMailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailViewRoute = AppMailViewRouteImport.update({
  id: '/$view',
  path: '/$view',
  getParentRoute: () => AppMailRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAddressesRoute = AppAdminAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDomainsRoute = AppAdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPeopleRoute = AppAdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppMailViewIndexRoute = AppMailViewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMailViewRoute,
} as any)
const AppMailViewMailboxIdThreadIdRoute =
  AppMailViewMailboxIdThreadIdRouteImport.update({
    id: '/$mailboxId/$threadId',
    path: '/$mailboxId/$threadId',
    getParentRoute: () => AppMailViewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppMailIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/$view': typeof AppMailViewRouteWithChildren
  '/admin/addresses': typeof AppAdminAddressesRoute
  '/admin/domains': typeof AppAdminDomainsRoute
  '/admin/people': typeof AppAdminPeopleRoute
  '/admin/': typeof AppAdminIndexRoute
  '/$view/': typeof AppMailViewIndexRoute
  '/$view/$mailboxId/$threadId': typeof AppMailViewMailboxIdThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppMailIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/addresses': typeof AppAdminAddressesRoute
  '/admin/domains': typeof AppAdminDomainsRoute
  '/admin/people': typeof AppAdminPeopleRoute
  '/admin': typeof AppAdminIndexRoute
  '/$view': typeof AppMailViewIndexRoute
  '/$view/$mailboxId/$threadId': typeof AppMailViewMailboxIdThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/_mail': typeof AppMailRouteWithChildren
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/_mail/$view': typeof AppMailViewRouteWithChildren
  '/_app/admin/addresses': typeof AppAdminAddressesRoute
  '/_app/admin/domains': typeof AppAdminDomainsRoute
  '/_app/admin/people': typeof AppAdminPeopleRoute
  '/_app/_mail/': typeof AppMailIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/_mail/$view/': typeof AppMailViewIndexRoute
  '/_app/_mail/$view/$mailboxId/$threadId': typeof AppMailViewMailboxIdThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/admin'
    | '/$view'
    | '/admin/addresses'
    | '/admin/domains'
    | '/admin/people'
    | '/admin/'
    | '/$view/'
    | '/$view/$mailboxId/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/admin/addresses'
    | '/admin/domains'
    | '/admin/people'
    | '/admin'
    | '/$view'
    | '/$view/$mailboxId/$threadId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/_mail'
    | '/_app/admin'
    | '/_app/_mail/$view'
    | '/_app/admin/addresses'
    | '/_app/admin/domains'
    | '/_app/admin/people'
    | '/_app/_mail/'
    | '/_app/admin/'
    | '/_app/_mail/$view/'
    | '/_app/_mail/$view/$mailboxId/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_mail': {
      id: '/_app/_mail'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppMailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_mail/': {
      id: '/_app/_mail/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppMailIndexRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/_mail/$view': {
      id: '/_app/_mail/$view'
      path: '/$view'
      fullPath: '/$view'
      preLoaderRoute: typeof AppMailViewRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/addresses': {
      id: '/_app/admin/addresses'
      path: '/addresses'
      fullPath: '/admin/addresses'
      preLoaderRoute: typeof AppAdminAddressesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/domains': {
      id: '/_app/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AppAdminDomainsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/people': {
      id: '/_app/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AppAdminPeopleRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_mail/$view/': {
      id: '/_app/_mail/$view/'
      path: '/'
      fullPath: '/$view/'
      preLoaderRoute: typeof AppMailViewIndexRouteImport
      parentRoute: typeof AppMailViewRoute
    }
    '/_app/_mail/$view/$mailboxId/$threadId': {
      id: '/_app/_mail/$view/$mailboxId/$threadId'
      path: '/$mailboxId/$threadId'
      fullPath: '/$view/$mailboxId/$threadId'
      preLoaderRoute: typeof AppMailViewMailboxIdThreadIdRouteImport
      parentRoute: typeof AppMailViewRoute
    }
  }
}

interface AppMailViewRouteChildren {
  AppMailViewIndexRoute: typeof AppMailViewIndexRoute
  AppMailViewMailboxIdThreadIdRoute: typeof AppMailViewMailboxIdThreadIdRoute
}

const AppMailViewRouteChildren: AppMailViewRouteChildren = {
  AppMailViewIndexRoute: AppMailViewIndexRoute,
  AppMailViewMailboxIdThreadIdRoute: AppMailViewMailboxIdThreadIdRoute,
}

const AppMailViewRouteWithChildren = AppMailViewRoute._addFileChildren(
  AppMailViewRouteChildren,
)

interface AppMailRouteChildren {
  AppMailViewRoute: typeof AppMailViewRouteWithChildren
  AppMailIndexRoute: typeof AppMailIndexRoute
}

const AppMailRouteChildren: AppMailRouteChildren = {
  AppMailViewRoute: AppMailViewRouteWithChildren,
  AppMailIndexRoute: AppMailIndexRoute,
}

const AppMailRouteWithChildren =
  AppMailRoute._addFileChildren(AppMailRouteChildren)

interface AppAdminRouteChildren {
  AppAdminAddressesRoute: typeof AppAdminAddressesRoute
  AppAdminDomainsRoute: typeof AppAdminDomainsRoute
  AppAdminPeopleRoute: typeof AppAdminPeopleRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAddressesRoute: AppAdminAddressesRoute,
  AppAdminDomainsRoute: AppAdminDomainsRoute,
  AppAdminPeopleRoute: AppAdminPeopleRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppMailRoute: typeof AppMailRouteWithChildren
  AppAdminRoute: typeof AppAdminRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppMailRoute: AppMailRouteWithChildren,
  AppAdminRoute: AppAdminRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
