/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppMailRouteImport } from './routes/_app._mail'
import { Route as AppSettingsRouteImport } from './routes/_app._settings'
import { Route as AppMailIndexRouteImport } from './routes/_app._mail.index'
import { Route as AppMailViewRouteImport } from './routes/_app._mail.$view'
import { Route as AppSettingsAdminRouteImport } from './routes/_app._settings.admin'
import { Route as AppMailViewIndexRouteImport } from './routes/_app._mail.$view.index'
import { Route as AppSettingsAdminIndexRouteImport } from './routes/_app._settings.admin.index'
import { Route as AppSettingsAdminAddressesRouteImport } from './routes/_app._settings.admin.addresses'
import { Route as AppSettingsAdminDomainsRouteImport } from './routes/_app._settings.admin.domains'
import { Route as AppSettingsAdminPeopleRouteImport } from './routes/_app._settings.admin.people'
import { Route as AppSettingsSettingsIndexRouteImport } from './routes/_app._settings.settings.index'
import { Route as AppSettingsSettingsAppearanceRouteImport } from './routes/_app._settings.settings.appearance'
import { Route as AppSettingsSettingsSignaturesRouteImport } from './routes/_app._settings.settings.signatures'
import { Route as AppMailViewMailboxIdThreadIdRouteImport } from './routes/_app._mail.$view.$mailboxId.$threadId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMailRoute = AppMailRouteImport.update({
  id: '/_mail',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/_settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMailIndexRoute = AppMailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMailRoute,
} as any)
const AppMailViewRoute = AppMailViewRouteImport.update({
  id: '/$view',
  path: '/$view',
  getParentRoute: () => AppMailRoute,
} as any)
const AppSettingsAdminRoute = AppSettingsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppMailViewIndexRoute = AppMailViewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMailViewRoute,
} as any)
const AppSettingsAdminIndexRoute = AppSettingsAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsAdminRoute,
} as any)
const AppSettingsAdminAddressesRoute =
  AppSettingsAdminAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AppSettingsAdminRoute,
  } as any)
const AppSettingsAdminDomainsRoute = AppSettingsAdminDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppSettingsAdminRoute,
} as any)
const AppSettingsAdminPeopleRoute = AppSettingsAdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppSettingsAdminRoute,
} as any)
const AppSettingsSettingsIndexRoute =
  AppSettingsSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsSettingsAppearanceRoute =
  AppSettingsSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsSettingsSignaturesRoute =
  AppSettingsSettingsSignaturesRouteImport.update({
    id: '/settings/signatures',
    path: '/settings/signatures',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppMailViewMailboxIdThreadIdRoute =
  AppMailViewMailboxIdThreadIdRouteImport.update({
    id: '/$mailboxId/$threadId',
    path: '/$mailboxId/$threadId',
    getParentRoute: () => AppMailViewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppMailIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/$view': typeof AppMailViewRouteWithChildren
  '/admin': typeof AppSettingsAdminRouteWithChildren
  '/admin/addresses': typeof AppSettingsAdminAddressesRoute
  '/admin/domains': typeof AppSettingsAdminDomainsRoute
  '/admin/people': typeof AppSettingsAdminPeopleRoute
  '/settings/appearance': typeof AppSettingsSettingsAppearanceRoute
  '/settings/signatures': typeof AppSettingsSettingsSignaturesRoute
  '/$view/': typeof AppMailViewIndexRoute
  '/admin/': typeof AppSettingsAdminIndexRoute
  '/settings/': typeof AppSettingsSettingsIndexRoute
  '/$view/$mailboxId/$threadId': typeof AppMailViewMailboxIdThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppMailIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/addresses': typeof AppSettingsAdminAddressesRoute
  '/admin/domains': typeof AppSettingsAdminDomainsRoute
  '/admin/people': typeof AppSettingsAdminPeopleRoute
  '/settings/appearance': typeof AppSettingsSettingsAppearanceRoute
  '/settings/signatures': typeof AppSettingsSettingsSignaturesRoute
  '/$view': typeof AppMailViewIndexRoute
  '/admin': typeof AppSettingsAdminIndexRoute
  '/settings': typeof AppSettingsSettingsIndexRoute
  '/$view/$mailboxId/$threadId': typeof AppMailViewMailboxIdThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/_mail': typeof AppMailRouteWithChildren
  '/_app/_settings': typeof AppSettingsRouteWithChildren
  '/_app/_mail/$view': typeof AppMailViewRouteWithChildren
  '/_app/_settings/admin': typeof AppSettingsAdminRouteWithChildren
  '/_app/_mail/': typeof AppMailIndexRoute
  '/_app/_settings/admin/addresses': typeof AppSettingsAdminAddressesRoute
  '/_app/_settings/admin/domains': typeof AppSettingsAdminDomainsRoute
  '/_app/_settings/admin/people': typeof AppSettingsAdminPeopleRoute
  '/_app/_settings/settings/appearance': typeof AppSettingsSettingsAppearanceRoute
  '/_app/_settings/settings/signatures': typeof AppSettingsSettingsSignaturesRoute
  '/_app/_mail/$view/': typeof AppMailViewIndexRoute
  '/_app/_settings/admin/': typeof AppSettingsAdminIndexRoute
  '/_app/_settings/settings/': typeof AppSettingsSettingsIndexRoute
  '/_app/_mail/$view/$mailboxId/$threadId': typeof AppMailViewMailboxIdThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/$view'
    | '/admin'
    | '/admin/addresses'
    | '/admin/domains'
    | '/admin/people'
    | '/settings/appearance'
    | '/settings/signatures'
    | '/$view/'
    | '/admin/'
    | '/settings/'
    | '/$view/$mailboxId/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/admin/addresses'
    | '/admin/domains'
    | '/admin/people'
    | '/settings/appearance'
    | '/settings/signatures'
    | '/$view'
    | '/admin'
    | '/settings'
    | '/$view/$mailboxId/$threadId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/_mail'
    | '/_app/_settings'
    | '/_app/_mail/$view'
    | '/_app/_settings/admin'
    | '/_app/_mail/'
    | '/_app/_settings/admin/addresses'
    | '/_app/_settings/admin/domains'
    | '/_app/_settings/admin/people'
    | '/_app/_settings/settings/appearance'
    | '/_app/_settings/settings/signatures'
    | '/_app/_mail/$view/'
    | '/_app/_settings/admin/'
    | '/_app/_settings/settings/'
    | '/_app/_mail/$view/$mailboxId/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_mail': {
      id: '/_app/_mail'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppMailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_settings': {
      id: '/_app/_settings'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_mail/': {
      id: '/_app/_mail/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppMailIndexRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/_mail/$view': {
      id: '/_app/_mail/$view'
      path: '/$view'
      fullPath: '/$view'
      preLoaderRoute: typeof AppMailViewRouteImport
      parentRoute: typeof AppMailRoute
    }
    '/_app/_settings/admin': {
      id: '/_app/_settings/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppSettingsAdminRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/_mail/$view/': {
      id: '/_app/_mail/$view/'
      path: '/'
      fullPath: '/$view/'
      preLoaderRoute: typeof AppMailViewIndexRouteImport
      parentRoute: typeof AppMailViewRoute
    }
    '/_app/_settings/admin/': {
      id: '/_app/_settings/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppSettingsAdminIndexRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/_settings/admin/addresses': {
      id: '/_app/_settings/admin/addresses'
      path: '/addresses'
      fullPath: '/admin/addresses'
      preLoaderRoute: typeof AppSettingsAdminAddressesRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/_settings/admin/domains': {
      id: '/_app/_settings/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AppSettingsAdminDomainsRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/_settings/admin/people': {
      id: '/_app/_settings/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AppSettingsAdminPeopleRouteImport
      parentRoute: typeof AppSettingsAdminRoute
    }
    '/_app/_settings/settings/': {
      id: '/_app/_settings/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/_settings/settings/appearance': {
      id: '/_app/_settings/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/_settings/settings/signatures': {
      id: '/_app/_settings/settings/signatures'
      path: '/settings/signatures'
      fullPath: '/settings/signatures'
      preLoaderRoute: typeof AppSettingsSettingsSignaturesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/_mail/$view/$mailboxId/$threadId': {
      id: '/_app/_mail/$view/$mailboxId/$threadId'
      path: '/$mailboxId/$threadId'
      fullPath: '/$view/$mailboxId/$threadId'
      preLoaderRoute: typeof AppMailViewMailboxIdThreadIdRouteImport
      parentRoute: typeof AppMailViewRoute
    }
  }
}

interface AppMailViewRouteChildren {
  AppMailViewIndexRoute: typeof AppMailViewIndexRoute
  AppMailViewMailboxIdThreadIdRoute: typeof AppMailViewMailboxIdThreadIdRoute
}

const AppMailViewRouteChildren: AppMailViewRouteChildren = {
  AppMailViewIndexRoute: AppMailViewIndexRoute,
  AppMailViewMailboxIdThreadIdRoute: AppMailViewMailboxIdThreadIdRoute,
}

const AppMailViewRouteWithChildren = AppMailViewRoute._addFileChildren(
  AppMailViewRouteChildren,
)

interface AppMailRouteChildren {
  AppMailViewRoute: typeof AppMailViewRouteWithChildren
  AppMailIndexRoute: typeof AppMailIndexRoute
}

const AppMailRouteChildren: AppMailRouteChildren = {
  AppMailViewRoute: AppMailViewRouteWithChildren,
  AppMailIndexRoute: AppMailIndexRoute,
}

const AppMailRouteWithChildren =
  AppMailRoute._addFileChildren(AppMailRouteChildren)

interface AppSettingsAdminRouteChildren {
  AppSettingsAdminAddressesRoute: typeof AppSettingsAdminAddressesRoute
  AppSettingsAdminDomainsRoute: typeof AppSettingsAdminDomainsRoute
  AppSettingsAdminPeopleRoute: typeof AppSettingsAdminPeopleRoute
  AppSettingsAdminIndexRoute: typeof AppSettingsAdminIndexRoute
}

const AppSettingsAdminRouteChildren: AppSettingsAdminRouteChildren = {
  AppSettingsAdminAddressesRoute: AppSettingsAdminAddressesRoute,
  AppSettingsAdminDomainsRoute: AppSettingsAdminDomainsRoute,
  AppSettingsAdminPeopleRoute: AppSettingsAdminPeopleRoute,
  AppSettingsAdminIndexRoute: AppSettingsAdminIndexRoute,
}

const AppSettingsAdminRouteWithChildren =
  AppSettingsAdminRoute._addFileChildren(AppSettingsAdminRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAdminRoute: typeof AppSettingsAdminRouteWithChildren
  AppSettingsSettingsAppearanceRoute: typeof AppSettingsSettingsAppearanceRoute
  AppSettingsSettingsSignaturesRoute: typeof AppSettingsSettingsSignaturesRoute
  AppSettingsSettingsIndexRoute: typeof AppSettingsSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAdminRoute: AppSettingsAdminRouteWithChildren,
  AppSettingsSettingsAppearanceRoute: AppSettingsSettingsAppearanceRoute,
  AppSettingsSettingsSignaturesRoute: AppSettingsSettingsSignaturesRoute,
  AppSettingsSettingsIndexRoute: AppSettingsSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppMailRoute: typeof AppMailRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppMailRoute: AppMailRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
